name: Build timer

on:
  push:
    tags:
      - '**'

jobs:
  parse-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      upload-url: ${{ steps.create-release.outputs.upload_url }}
    steps:
      - name: Checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - id: version
        run: echo "version=$(git describe --exact-match --tags)" >> "$GITHUB_OUTPUT"
      - run: echo ${{ steps.version.outputs.version }} > timer-version
      - uses: ncipollo/release-action@v1.16.0
        id: create-release
        with:
          draft: true
          name: Timer ${{ steps.version.outputs.version }}
      - run: mv pyevilemu/evilemu . ; rm -rf pyevilemu
      - name: Upload timer
        uses: actions/upload-artifact@v4
        with:
          name: timer-source
          path: '.'
          include-hidden-files: true
      - run: zip -r timer-source.zip .
      - name: Upload to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: ${{ format('gh release upload {0} timer-source.zip', github.ref_name) }}

  build-timer-linux:
    runs-on: ubuntu-latest
    needs: parse-version
    steps:
      - name: Download timer
        uses: actions/download-artifact@v4
        with:
          name: timer-source
          path: '.'
      - name: Create executable
        id: build
        uses: kbranch/pyinstaller-action@main
        with:
          python_ver: '3.12'
          spec: 'timer.spec'
          requirements: 'requirements.txt'
      - run: ${{ format('mv "{0}/timer" ./timer-linux', steps.build.outputs.executable_path) }}
      - name: Upload to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: ${{ format('gh release upload {0} timer-linux', github.ref_name) }}

  build-timer-windows:
    runs-on: windows-latest
    needs: parse-version
    steps:
      - name: Download timer
        uses: actions/download-artifact@v4
        with:
          name: timer-source
          path: '.'
      - name: Create executable
        id: build
        uses: kbranch/pyinstaller-action@main
        with:
          python_ver: '3.12'
          spec: 'timer.spec'
          requirements: 'requirements.txt'
      - run: ${{ format('mv "{0}\timer.exe" .\timer-windows.exe', steps.build.outputs.executable_path) }}
      - name: Upload to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: ${{ format('gh release upload {0} timer-windows.exe', github.ref_name) }}

  build-timer-macos:
    runs-on: macos-latest
    needs: parse-version
    steps:
      - name: Download timer
        uses: actions/download-artifact@v4
        with:
          name: timer-source
          path: '.'
      - name: Create executable
        id: build
        uses: kbranch/pyinstaller-action@main
        with:
          python_ver: '3.12'
          spec: 'timer.spec'
          requirements: 'requirements.txt'
      - run: ${{ format('mv "{0}/timer" ./timer-macos', steps.build.outputs.executable_path) }}
      - name: Upload to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: ${{ format('gh release upload {0} timer-macos', github.ref_name) }}
